FIX for view-only mode (yform permssion)
FriendsOfREDAXO/yform_usability pull request #105
Opened 2022-07-05 08:40 UTC by bitshiftersgmbh

preventing appearance of duplicate action button in view-only mode
TODO: double check at `public static function duplicateRow()`

2022-10-26 19:54 UTC, alxndr-w commented
Wie sieht es mit diesem PR aus?

2022-10-27 09:28 UTC, tyrant88 requested changes
Kannst du da bitte noch ein `$this->hasDataPageFunction('add')` in die Bedingung aufnehmen?

2022-10-27 09:43 UTC, alxndr-w commented
@tyrant88 das habe ich jetzt vorgenommen.

2022-10-27 09:44 UTC, alxndr-w commented
Ich weiß halt nicht, was 

> TODO: double check at public static function duplicateRow()

von @bitshiftersgmbh heißen soll.

2022-10-27 09:47 UTC, bitshiftersgmbh commented
> TODO: double check at public static function duplicateRow()

heißt, dass man bei der eigentlichen ausführenden Methode für das Duplizieren (`duplicateRow()`) den Check aus meiner Sicht auch nochmal bräuchte, da die ja theoretisch über URL-Params auch ohne den Button triggerbar ist oder irre ich mich da? Falls ja, ignoriert's einfach.

2022-10-27 12:00 UTC, tyrant88 commented
okay, ich hab den check noch in duplicateRow() eingebaut.

2022-10-27 12:25 UTC, tyrant88 commented
so, das mit der zusatzbedingung war Bödsinn, an der Stelle komme ich gar nicht an das manager Objekt ran -- ist wieder raus

2022-10-27 12:25 UTC, tyrant88 approved these changes
jetzt sollte es passen

2022-10-27 12:26 UTC, bitshiftersgmbh commented
> so, das mit der zusatzbedingung war Bödsinn, an der Stelle komme ich gar nicht an das manager Objekt ran -- ist wieder raus

Ich hatte das schon befürchtet, steck aber gerade nicht so tief im Code drin. Der ursprüngliche Check sollte passen denk ich. ;)

2022-10-27 12:28 UTC, merged