addStatusToggle Typehint wieder entfernt
FriendsOfREDAXO/yform_usability pull request #132
Opened 2023-02-21 07:46 UTC by michael-kreatif

Rückgabe kann auch rex_yform_list sein, nicht nur rex_list. 
Siehe Code Stellen: 

https://github.com/yakamara/redaxo_yform/blob/ced8f147a76caae745281fa112b3f1a17a807efd/plugins/manager/fragments/yform/manager/page/list.php#L16
https://github.com/yakamara/redaxo_yform/blob/ced8f147a76caae745281fa112b3f1a17a807efd/plugins/manager/fragments/yform/manager/page/list.php#L175
https://github.com/FriendsOfREDAXO/yform_usability/blob/main/boot.php#L65

2023-02-21 15:08 UTC, tyrant88 commented
Es ist eigentlich immer eine rex_yform_list würde ich behaupten.
Weiß gerade nicht, warum das bei mir keinen Fehler geworfen hat...

Man könnte auch auf $ep->setSubject() gehen und dann als return_type void nehmen...

2023-02-22 07:17 UTC, michael-kreatif commented
@tyrant88 Stimmt, danke, laut Code müsste es eigentlich immer rex_yform_list sein, außer es gibt noch ein anderes addon, das den EP 'YFORM_DATA_LIST' triggert, aber das glaube ich nicht.

2023-02-22 10:00 UTC, tyrant88 commented
Ich glaube das widerspräche dem Konzept der Extension Points.

2023-02-23 11:19 UTC, tyrant88 commented
Ah, sehe gerade im yform changelog für Version 4:
"rex_yform_list ergänzt. Ersetzt rex_list und kann YORM Queries entgegennehmen"
Deshalb hatte Thomas Blum wohl rex_list im Code...

2023-02-23 11:32 UTC, tyrant88 requested changes
kannst/willst du das noch schnell auf rex_yform_list ändern?

2023-02-27 13:25 UTC, goldfoot commented
Typsicherheit ist ja ansich nicht schlecht und in PHP 8 sind [Union Types](https://wiki.php.net/rfc/union_types_v2) erlaubt. Ich schlage daher vor, beide Typen zuzulassen und den PR in "addStatusToggle return type rex_yform_list zulassen" umzubenennen:

```php
protected static function addStatusToggle($list, $table): \rex_list | \rex_yform_list
    {
        /** @var \rex_list | \rex_yform_list $list */
       // ...
    }
```

2023-02-27 13:56 UTC, tyrant88 commented
@goldfoot ? 
Wir haben doch bereits geklärt, dass ab yform 4 (was in der package.yml vorrausgesetzt wird) der return type "rex_yform_list" ist.

Eventuell merge ich den PR so wie er ist, wenn der Ersteller ihn nicht zeitnah anpasst, deshalb bleibt der Titel erstmal. :-)

2023-02-27 14:15 UTC, tyrant88 approved these changes

2023-02-27 14:17 UTC, merged

2023-02-27 14:34 UTC, goldfoot commented
@tyrant88 Stimmt, ich hatte die Beschränkung der yForm Version nicht berücksichtigt und bin daher davon ausgegangen, dass auch yForm 3 noch möglich sei.